// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]args) {
	    int numberOfTimes = Integer.parseInt(args[0]);//מספר הניסניונות
		int above =0;
		int below =0;
		for (int i = 0; i < numberOfTimes; i++)// רץ כמספר הנסיונות
		{
			if (Math.random() > 0.5) // אם גדול מחצי
			{
				above++;
			}
			else // במקרה שקטן או שווה לחצי
			{
				below++;
			}
		}
		double ratio = (double)above/below;
		System.out.println("> 0.5: " + above + " times");
		System.out.println("<= 0.5: " + below + " times");
		System.out.println("Ratio: "+ ratio);
	}
}
